### ISSUE TITLE
Write a tool to set up the initial admin user

### ISSUE THREAD

**Issue by JRIngram** [JRIngram/CoffeeTable#5]
Write a command-line tool in Node that a user can run during set-up.

In addition to having the same functionality as `createDB.js`. This tool should:
* Insert prompt the user to enter the database name and database URL or leave these as the default values
* Create an initial admin user:
    * Prompt the user for a username .
    * Prompt the user for: email, first name, last name.
    * Prompt the user for a password and hash the password.
    * Insert this user into the users collection with the role "admin".

**Comment by Lisiadito** [comment]
I'm interested in doing this. 
Do you care which command line parser I use? I would popably use `yargs` but I'm also open to work with another parser or do it completely without if you want to keep the dependency list short.

**Comment by JRIngram** [comment]
I don't mind which parser you use, so long as the code is fairly maintainable! :)

**Comment by JRIngram** [comment]
Thanks for the help! Good work! And thanks for opening the other issues too!
