### ISSUE TITLE
Review & fix package vulnerabilities

### ISSUE THREAD

**Issue by Lisiadito** [JRIngram/CoffeeTable#6]
At the moment NPM finds `found 2799 vulnerabilities (3 low, 2795 high, 1 critical)` 
To get more details run `npm audit` and possibly automatically fix them with `npm audit fix`.
@JRIngram you can maybe use dependabot under the security tab here on github. it will automatically open a PR for dependency fixes if possible.

**Comment by JRIngram** [comment]
Completed as Part of PR #10
